name: media_stream_platform
description: A cross-platform media streaming service
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  video_player: ^2.8.2
  cached_network_image: ^3.3.1
  http: ^1.2.0
  wakelock_plus: ^1.1.4  # Added for video player controls

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true