service: article-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    ARTICLES_TABLE: ${self:service}-${opt:stage, self:provider.stage}

resources:
  Resources:
    ArticlesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ARTICLES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: categoryId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: CategoryIndex
            KeySchema:
              - AttributeName: categoryId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

functions:
  getArticle:
    handler: src/handlers/getArticle.handler
    events:
      - http:
          path: /articles/{id}
          method: get
          cors: true
          authorizer: aws_iam

  listArticles:
    handler: src/handlers/listArticles.handler
    events:
      - http:
          path: /articles
          method: get
          cors: true
          authorizer: aws_iam