service: content-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

resources:
  Resources:
    ContentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

functions:
  getContent:
    handler: src/handlers/getContent.handler
    events:
      - http:
          path: /content/{id}
          method: get
          cors: true

  listContent:
    handler: src/handlers/listContent.handler
    events:
      - http:
          path: /content
          method: get
          cors: true
